openapi: 3.0.1
info:
    title: Hello World Python Example
    version: 1.0.0
servers:
  - url: 'https://localhost:9000/helloworld'
    description: Local server running test api

paths:
  /helloworld:
    get:
      tags:
        - Hello World 
      summary: Asks for Hello World! example
      
      responses:
        '200':
          description: Will return "Hello World!" on success
          content:
            text/plain:
              schema:
                type: string
                example: Hello World

